/**
 * Set de iconos de Bifrost, renderizado con **Phosphor Icons (weight duotone)** — una sola línea
 * gráfica coherente, licencia **MIT** (apta para el producto OSS, a diferencia de FontAwesome Pro que
 * prohíbe redistribuir sus iconos en proyectos open-source). Sin registry pago ni token: `pnpm install`
 * funciona en cualquier fork/CI sin secretos.
 *
 * Cada icono es un componente Vue (root `<svg>`), así que AppIcon usa `<component :is>` en vez de
 * `v-html` — más seguro (sin inyección de markup) y sin el hack de CSP de svg-core.
 */
import type { Component } from 'vue';
import {
  PhList,
  PhMagnifyingGlass,
  PhGear,
  PhTray,
  PhStar,
  PhClock,
  PhPaperPlaneTilt,
  PhFile,
  PhArchive,
  PhShieldCheck,
  PhTrash,
  PhArrowBendUpLeft,
  PhArrowBendDoubleUpLeft,
  PhArrowBendUpRight,
  PhDotsThreeVertical,
  PhMapPin,
  PhPaperclip,
  PhX,
  PhCaretDown,
  PhCaretLeft,
  PhCaretRight,
  PhPlus,
  PhPencilSimple,
  PhCalendarBlank,
  PhTag,
  PhArrowsClockwise,
  PhMoon,
  PhSun,
  PhQuestion,
  PhSquaresFour,
  PhBell,
  PhCheck,
  PhDownloadSimple,
  PhFunnelSimple,
  PhUser,
  PhUsers,
  PhLock,
  PhGlobe,
  PhEnvelope,
  PhArrowLeft,
  PhPrinter,
  PhSignOut,
  PhCircle,
  PhPalette,
  PhDatabase,
  PhBriefcase,
  PhCopy,
  PhArrowSquareOut,
  PhArrowRight,
  PhBuildings,
  PhSlidersHorizontal,
  PhVideoCamera,
  PhPhone,
  PhImage,
  PhUploadSimple,
  PhEye,
  PhCalendarCheck,
  PhListBullets,
  PhLink,
  PhMicrophone,
  PhMicrophoneSlash,
  PhVideoCameraSlash,
  PhScreencast,
  PhWifiSlash,
  PhShareNetwork,
} from '@phosphor-icons/vue';

// Mapa nombre-lógico → componente Phosphor. Las claves son la API pública estable (mismas del set
// anterior lucide/FA): un `<AppIcon name="…" />` existente no cambia. El glifo pasa a Phosphor duotone.
export const ICONS = {
  menu: PhList,
  search: PhMagnifyingGlass,
  settings: PhGear,
  inbox: PhTray,
  star: PhStar,
  clock: PhClock,
  send: PhPaperPlaneTilt,
  file: PhFile,
  archive: PhArchive,
  shield: PhShieldCheck,
  trash: PhTrash,
  reply: PhArrowBendUpLeft,
  replyAll: PhArrowBendDoubleUpLeft,
  forward: PhArrowBendUpRight,
  more: PhDotsThreeVertical,
  mapPin: PhMapPin,
  paperclip: PhPaperclip,
  x: PhX,
  chevronDown: PhCaretDown,
  chevronLeft: PhCaretLeft,
  chevronRight: PhCaretRight,
  plus: PhPlus,
  pencil: PhPencilSimple,
  calendar: PhCalendarBlank,
  tag: PhTag,
  refresh: PhArrowsClockwise,
  moon: PhMoon,
  sun: PhSun,
  help: PhQuestion,
  grid: PhSquaresFour,
  bell: PhBell,
  check: PhCheck,
  download: PhDownloadSimple,
  filter: PhFunnelSimple,
  user: PhUser,
  users: PhUsers,
  lock: PhLock,
  globe: PhGlobe,
  mail: PhEnvelope,
  arrowLeft: PhArrowLeft,
  printer: PhPrinter,
  logout: PhSignOut,
  dot: PhCircle,
  palette: PhPalette,
  database: PhDatabase,
  briefcase: PhBriefcase,
  copy: PhCopy,
  externalLink: PhArrowSquareOut,
  arrowRight: PhArrowRight,
  building: PhBuildings,
  sliders: PhSlidersHorizontal,
  video: PhVideoCamera,
  phone: PhPhone,
  image: PhImage,
  upload: PhUploadSimple,
  eye: PhEye,
  calendarClock: PhCalendarCheck,
  list: PhListBullets,
  link: PhLink,
  // Iconos de la videollamada (Bifrost Meet) — agregados en main tras ramear el PR.
  mic: PhMicrophone,
  micOff: PhMicrophoneSlash,
  videoOff: PhVideoCameraSlash,
  screenShare: PhScreencast,
  // PWA: sin conexión / compartir (hint de instalación en iOS).
  wifiSlash: PhWifiSlash,
  share: PhShareNetwork,
} as const satisfies Record<string, Component>;

/** Nombres válidos de icono (unión cerrada del mapa). El nuevo código debe usar este tipo. */
export type IconName = keyof typeof ICONS;
